services:
  database:
    image: postgres:16.9-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    container_name: "db_test"
    image: postgres:16.9-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    ports:
      - "5433:5432"

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

  web-app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: core.settings
      REDIS_URL: ${REDIS_URL}
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./src:/app/src
    env_file:
      - .env

  celery-worker:
    build: .
    command: celery -A core worker --loglevel=info
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: core.settings
      REDIS_URL: ${REDIS_URL}
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./src:/app/src
    env_file:
      - .env

  telegram-bot:
    build: ./bot
    command: python bot.py
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      POSTGRES_HOST: database
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./bot:/bot


volumes:
  postgres_data:
